name: Preview

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  preview-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: preview
    outputs:
      url: ${{ steps.page.outputs.deployment-url }}
    steps:
      - uses: actions/checkout@v5
      - uses: shiron-dev/actions/setup-node@3478cc44402c5c590ce6732554e621558ac6d6e5 # v1.5.0
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run build
        run: pnpm run build
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3
        id: page
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./dist --project-name=snct-2025-hp
      - name: Get first line of commit message
        id: commit-message
        uses: actions/github-script@v8
        with:
          script: |
            const message = context.payload.head_commit.message;
            const firstLine = message.split('\n')[0];
            core.setOutput('firstLine', firstLine);
      - name: Notify Slack - Preview Deploy
        uses: slackapi/slack-github-action@v2.1.1
        if: github.event_name == 'push'
        with:
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "🔍 高専祭2025HP プレビュー環境デプロイ完了",
              "attachments": [
                {
                  "color": "warning",
                  "fields": [
                    {
                      "title": "プレビューURL",
                      "value": "<${{ steps.page.outputs.deployment-url }}|${{ steps.page.outputs.deployment-url }}>",
                      "short": false
                    },
                    {
                      "title": "デプロイ先",
                      "value": "Cloudflare Pages (Preview)",
                      "short": true
                    },
                    {
                      "title": "プロジェクト名",
                      "value": "snct-2025-hp",
                      "short": true
                    },
                    {
                      "title": "ブランチ",
                      "value": "${{ github.ref_name }}",
                      "short": true
                    },
                    {
                      "title": "コミット",
                      "value": "<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ steps.commit-message.outputs.firstLine }}>",
                      "short": true
                    },
                    {
                      "title": "実行者",
                      "value": "${{ github.actor }}",
                      "short": true
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Comment
        uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2.8.2
        if: github.event_name == 'pull_request'
        with:
          message-id: cloudflare-deploy
          message: |
            ### Preview

            |  Name | Link |
            |---------------------------------|------------------------|
            |<span aria-hidden="true">🔨</span> Latest commit | ${{ github.sha }} |
            |<span aria-hidden="true">😎</span> Deploy Preview Url | [${{ steps.page.outputs.deployment-url }}](${{ steps.page.outputs.deployment-url }}) |
            ---
  lighthouse:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: preview-deploy
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v5
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@fcd65974f7c4c2bf0ee9d09b84d2489183c29726 # v12
        id: lighthouse_audit
        with:
          urls: |
            ${{ needs.preview-deploy.outputs.url }}
          uploadArtifacts: true
          temporaryPublicStorage: true
      - uses: actions/github-script@v8
        id: github_script
        with:
          script: |
            const script = (await import(`${process.env.GITHUB_WORKSPACE}/.github/scripts/lighthouse.js`)).default;
            const manifest = ${{ steps.lighthouse_audit.outputs.manifest }};
            return script(manifest);
          result-encoding: string
      - name: Comment
        uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2.8.2
        with:
          message-id: lightouse-audit
          message: |
            ### Lightouse Audit

            ${{ steps.github_script.outputs.result }}
  preview-storybook-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: preview
    if: github.event_name == 'pull_request'
    outputs:
      url: ${{ steps.page.outputs.deployment-url }}
    steps:
      - uses: actions/checkout@v5
      - uses: shiron-dev/actions/setup-node@3478cc44402c5c590ce6732554e621558ac6d6e5 # v1.5.0
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run build:storybook
        run: pnpm run build:storybook
      - name: Run build
        run: pnpm run build
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3
        id: page
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./storybook-static --project-name=snct-2025-hp-sb
      - name: Comment
        uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2.8.2
        with:
          message-id: cloudflare-sb-deploy
          message: |
            ### Storybook Preview

            |  Name | Link |
            |---------------------------------|------------------------|
            |<span aria-hidden="true">🔨</span> Latest commit | ${{ github.sha }} |
            |<span aria-hidden="true">😎</span> Deploy Preview Url | [${{ steps.page.outputs.deployment-url }}](${{ steps.page.outputs.deployment-url }}) |
            ---
