name: Save VRT

on:
  push:
    branches:
      - main

jobs:
  vrt-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: shiron-dev/actions/setup-node@3478cc44402c5c590ce6732554e621558ac6d6e5 # v1.5.0
      - name: Run install
        run: |
          pnpm install --frozen-lockfile
      - name: Run run:storycap
        run: |
          pnpm run run:storycap
      - name: Save snapshot on main branch
        run: pnpm reg-suit run --no-report
        env:
          REG_SUIT_ACTUAL_KEY: ${{ github.sha }}
          AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
